# Generated by Django 6.0.3 on 2026-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketattachment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('tickets', 'Tickets'), ('users', 'Usuarios'), ('companies', 'Empresas'), ('support', 'Soporte'), ('notifications', 'Notificaciones')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'Ver'), ('view_all', 'Ver todos'), ('create', 'Crear'), ('edit', 'Editar'), ('delete', 'Eliminar')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_assign_tickets',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_companies',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_tickets',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_users',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='tickets.permission'),
        ),
    ]
