# Generated by Django 6.0.3 on 2026-03-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_permission_remove_role_can_assign_tickets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sla',
            old_name='resolution_hours',
            new_name='resolution_minutes',
        ),
        migrations.RenameField(
            model_name='sla',
            old_name='response_hours',
            new_name='response_minutes',
        ),
    ]
