# Generated by Django 6.0.3 on 2026-03-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_resolution_hours_sla_resolution_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='assigment_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN PROGRESO', 'En espera del cliente'), ('EN PROGRESO', 'En espera de soporte'), ('CERRADO', 'Cerrado')], default='NUEVO', max_length=20),
        ),
    ]
