# Generated by Django 6.0.3 on 2026-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_sla_assigment_minutes_alter_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sla',
            old_name='assigment_minutes',
            new_name='assignment_minutes',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En proceso'), ('WAITING_CLIENT', 'Esperando cliente'), ('WAITING_SUPPORT', 'Esperando soporte'), ('CERRADO', 'Cerrado')], default='NUEVO', max_length=20),
        ),
    ]
