# Generated by Django 5.0.6 on 2026-04-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_brand_alter_ticket_options_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
