# Generated by Django 5.0.6 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_profile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
